# -*- coding: utf-8 -*-
"""CHATBOTP9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZOT7msYmccn_za2EpoZpG-8lvr468fI_
"""

!pip install streamlit
!pip install -q langchain-openai langchain-core langchain-community langchain-chroma langchain-text-splitters unstructured chromadb tiktoken lxml beautifulsoup4 streamlit
import streamlit as st
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.document_loaders import UnstructuredHTMLLoader
from langchain_core.runnables import RunnablePassthrough
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma

# -----------------------------------
# Page Configuration
# -----------------------------------
st.set_page_config(
    page_title="Samsung Washing Machine Chatbot",
    page_icon="🤖",
    layout="wide"
)

st.title("🤖 Samsung Washing Machine Chatbot")
st.markdown("Ask anything about Samsung Washing Machine modes.")

# -----------------------------------
# Sidebar
# -----------------------------------
with st.sidebar:
    st.header("🔑 API Configuration")

    api_key = st.text_input(
        "Enter OpenAI API Key",
        type="password",
        placeholder="sk-..."
    )

    st.markdown("---")
    st.info(
        "Your API key is used only for this session and is never stored."
    )

if not api_key:
    st.warning("Please enter your OpenAI API Key to continue.")
    st.stop()

# -----------------------------------
# Load LLM
# -----------------------------------
llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0,
    api_key=api_key
)

embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small",
    api_key=api_key
)

# -----------------------------------
# Load HTML
# -----------------------------------
@st.cache_resource
def load_vectorstore():

    loader = UnstructuredHTMLLoader("samsung.html")
    docs = loader.load()

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200
    )

    splits = splitter.split_documents(docs)

    vectorstore = Chroma.from_documents(
        documents=splits,
        embedding=embeddings
    )

    return vectorstore

vectorstore = load_vectorstore()

retriever = vectorstore.as_retriever()

# -----------------------------------
# Prompt
# -----------------------------------
prompt = ChatPromptTemplate.from_template(
"""
You are an assistant for question-answering tasks.

Use the following retrieved context to answer the user's question.

If you don't know the answer, simply say you don't know.

Answer in a maximum of three concise sentences.

Question:
{question}

Context:
{context}

Answer:
"""
)

rag_chain = (
    {
        "context": retriever,
        "question": RunnablePassthrough()
    }
    | prompt
    | llm
)

# -----------------------------------
# Chat History
# -----------------------------------
if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# -----------------------------------
# Chat Input
# -----------------------------------
question = st.chat_input("Ask a question about Samsung Washing Machine...")

if question:

    st.session_state.messages.append(
        {"role": "user", "content": question}
    )

    with st.chat_message("user"):
        st.markdown(question)

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            answer = rag_chain.invoke(question).content
            st.markdown(answer)

    st.session_state.messages.append(
        {"role": "assistant", "content": answer}
    )

# -----------------------------------
# Clear Chat
# -----------------------------------
st.sidebar.markdown("---")

if st.sidebar.button("🗑 Clear Chat"):
    st.session_state.messages = []
    st.rerun()